# Generated by Django 4.0.3 on 2022-04-17 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_mybasket_mybasket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybasket',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mybasket',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
